import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-course-cards',
  imports: [CommonModule],
  templateUrl: './course-cards.html',
  styleUrl: './course-cards.scss'
})
export class CourseCards {
  courses = [
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: 'svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: 'svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: 'svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: 'svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: 'svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: 'svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: 'svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: 'svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: 'svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: 'svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: 'svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: 'svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
    {
      title: 'دوره آموزشی آنلاین سبک‌های معماری نرم‌افزار',
      imagePath: 'svg/course-card/behestan.png',
      date: '۱۴ مهر ۱۴۰۳',
      day: 'دوشنبه',
      time: 'ساعت ۲۱',
      mode: 'حضوری',
      location: 'خرمدره',
      price: '۵۰۰/۰۰۰',
      currency: 'تومان',
      organizerImage: 'svg/course-card/tehran-uni.svg',
      organizer: 'دانشگاه تهران',
    },
  ];
  
}
